version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - echo "Set region"
      - export AWS_DEFAULT_REGION=ap-south-1
      - echo "Check IAM role"
      - aws sts get-caller-identity 

      - echo "Update kubeconfig"
      - aws eks update-kubeconfig --region ap-south-1 --name vite-cluster

      - echo "Force authentication"
      - aws eks get-token --cluster-name vite-cluster --region ap-south-1

      - echo "Test access"
      - kubectl get nodes
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t dugyalaravali28/vite-app:latest .
  post_build:
    commands:
      - echo "Pushing image..."
      - docker push dugyalaravali28/vite-app:latest
      - echo "Deploying directly from CodeBuild..."
      # We do the deployment here instead of using a separate Pipeline stage
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml 

artifacts:
  files:
    - '**/*'
