version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - aws eks update-kubeconfig --region ap-south-1 --name vite-cluster
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t dugyalaravali28/vite-app:latest
  post_build:
    commands:
      - echo "Pushing image..."
      - docker push dugyalaravali28/vite-app:latest
      - echo "Deploying directly from CodeBuild..."
      # We do the deployment here instead of using a separate Pipeline stage
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml 

artifacts:
  files:
    - '**/*'
